### ISSUE TITLE
Cannot load page cool_timeline_page

### ISSUE THREAD

**Issue by zner0L** [narinder9/cool-timeline#1]
It seems that there is some bug in the settings page. When you try to open it from the Plugins page I get this error. I use Wordpress 4.4, the problem persists even after deactivating all other plugins. Even changing the theme has no effect. I populated the stories with example content.

**Comment by narinder9** [comment]
Hi,
I have tested plugin settings link in my end. It is working fine.Please send me your working demo link or 
screenshots.
